stages:
  - build
  - deploy

build:
  stage: build
  tags: 
    - docker
  image: node:10.16.3
  script:
    - apt-get update && apt-get install -y libssl-dev liblz4-dev libsasl2-dev libpthread-stubs0-dev build-essential pkg-config
    - npm install
    - npm run-script build
  cache:
    key: build-cache-graphql
    paths:
    - node_modules/
  artifacts:
    paths:
      - dist/
  
deploy:
  stage: deploy
  only:
    - master
  tags:
    - shell
  script:
    - docker build -t visual-cep-pattern_graphql:0.1 .
    - docker kill visual-cep-pattern_graphql || true
    - docker rm visual-cep-pattern_graphql || true
    - docker run -p 4000:4000 --restart=always -d --name=visual-cep-pattern_graphql -v visual-cep-pattern_grapqlnode_modules:/node_modules visual-cep-pattern_graphql:0.1
