stages:
  - build
  - deploy

build:
  stage: build
  tags: 
    - docker
  image: node:10.16.3
  script: 
    - npm install
    - npm run-script build
    - ls -la
  artifacts:
    paths:
      - dist/
  
deploy:
  stage: deploy
  tags:
    - shell
  script:
    - docker build -t visualcepgraphql:0.1 .
    - docker kill visualcepgraphql || true
    - docker rm visualcepgraphql || true
    - docker run -p 4000:4000 --restart=always -d --name=visualcepgraphql visualcepgraphql:0.1
